{
 "title": "下机数据状态",
 "tags": [ "cell" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "cell",
    "label": "CELL",
    "query": "SHOW TAG VALUES WITH KEY = \"cell\""
   },
   {
    "name": "barcode",
    "label": "Barcode",
    "query": "SHOW TAG VALUES WITH KEY = \"barcode\" WHERE cell =~ /$cell/"
   },
   { "name": "read_len_min", "label": "Read length min", "query": "0" },
   { "name": "read_len_max", "label": "Read length max", "query": "5000" },
   {
    "name": "read_len_depth",
    "label": "Read length (depth)",
    "query": "SHOW TAG VALUES WITH KEY = \"read_len\" WHERE cell =~ /$cell/"
   },
   { "name": "galaxy_api", "label": "Galaxy_API", "query": "www.baidu.com" },
   { "name": "fastq_dir", "label": "fastq dir", "query": "/data/basecalled/$cell" }
  ]
 },
 "panels": [
  {
   "title": "总览",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Read 长度分布",
     "type": "graph",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "长度",
       "measurement": "csv_tail",
       "query": "SELECT \"read_len\" FROM \"csv_tail\" WHERE (\"read_len\" >= $read_len_min) AND $timeFilter",
       "select": [
        [
         { "params": [ "read_len" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "read_len", "operator": ">", "value": "$read_len_min" },
        { "condition": "AND", "key": "read_len", "operator": "<", "value": "$read_len_max" }
       ]
      }
     ]
    },
    {
     "title": "深度分布",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 11, "y": 1 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "$tag_position",
       "groupBy": [
        { "params": [ "position" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "reads_depth_stats",
       "query": "SELECT max(\"value\") FROM \"reads_depth_stat\" WHERE $timeFilter GROUP BY \"position\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "read_len", "operator": "=~", "value": "/^$read_len_depth$/" },
        { "condition": "AND", "key": "cell", "operator": "=~", "value": "/^$cell$/" }
       ]
      }
     ]
    },
    {
     "title": "Fastq 文件数量",
     "type": "singlestat",
     "gridPos": { "h": 8, "w": 3, "x": 21, "y": 1 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "directory" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "filecount",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "directory", "operator": "=", "value": "$fastq_dir" }
       ]
      }
     ]
    },
    {
     "title": "Percent",
     "type": "graph",
     "gridPos": { "h": 7, "w": 11, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "csv_tail",
       "query": "SELECT mean(\"num_matches\")/mean(\"mapping_len\")*100  FROM \"csv_tail\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "mapping_len" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Reads",
     "type": "graph",
     "gridPos": { "h": 7, "w": 10, "x": 11, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "csv_tail",
       "select": [
        [
         { "params": [ "read_len" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "read_len" ], "type": "alias" }
        ]
       ]
      }
     ]
    },
    {
     "title": "Fastq 文件大小",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 3, "x": 21, "y": 9 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" }
       ],
       "measurement": "filecount",
       "select": [
        [
         { "params": [ "size_bytes" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "directory", "operator": "=", "value": "$fastq_dir" }
       ]
      }
     ]
    },
    {
     "title": "Fastq 文件详情",
     "type": "table",
     "gridPos": { "h": 7, "w": 21, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "measurement": "fastq_watch",
       "select": [
        [
         { "params": [ "path" ], "type": "field" }
        ],
        [
         { "params": [ "size" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "cell", "operator": "=~", "value": "/^$cell$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "$barcode",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "repeat": "barcode",
   "collapsed": true,
   "panels": [
    {
     "title": "$barcode Reads 长度分布",
     "type": "graph",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "measurement": "csv_tail",
       "select": [
        [
         { "params": [ "read_len" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "barcode", "operator": "=~", "value": "/^$barcode$/" },
        { "condition": "AND", "key": "read_len", "operator": ">", "value": "$read_len_min" },
        { "condition": "AND", "key": "read_len", "operator": "<", "value": "$read_len_max" }
       ]
      }
     ]
    },
    {
     "title": "$barcode 深度分布",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 11, "y": 2 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "$tag_position",
       "groupBy": [
        { "params": [ "position" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "reads_depth_stats",
       "query": "SELECT max(\"value\") FROM \"reads_depth_stat\" WHERE (\"barcode\" = 'NB01' AND \"depth\" = '$read_length') AND $timeFilter GROUP BY \"position\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "barcode", "operator": "=~", "value": "/^$barcode$/" },
        { "condition": "AND", "key": "read_len", "operator": "=~", "value": "/^$read_len_depth$/" },
        { "condition": "AND", "key": "cell", "operator": "=~", "value": "/^$cell$/" }
       ]
      }
     ]
    }
   ]
  }
 ]
}