{
 "title": "样本实验结果",
 "tags": [ "实验结果" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "sample_query", "label": "样本名称查询" },
   {
    "name": "sample_name",
    "label": "样本名称",
    "query": "show tag values from sample_info with key = \"sample_name\" where sample_name =~ /$sample_query/"
   },
   {
    "name": "ont_barcode",
    "label": "ONT-Barcode",
    "query": "show tag values from sample_info_ont with key = \"barcode\" where sample_name = '$sample_name'"
   },
   {
    "name": "ont_cell",
    "label": "ONT-Cell",
    "query": "show tag values from sample_info_ont with key = \"cell\" where sample_name = '$sample_name'"
   },
   {
    "name": "pcr_run_well",
    "label": "PCR-孔位",
    "query": "show tag values from sample_info_pcr with key = \"run_well\" where sample_name = '$sample_name'"
   },
   {
    "name": "immunochromatography_sample_id",
    "label": "免疫层析样本ID",
    "query": "show tag values from sample_info_immunochromatography with key = \"sample_id\" where sample_name = '$sample_name'"
   },
   {
    "name": "immunochromatography_report_time",
    "label": "免疫层析实验编号",
    "query": "show tag values from sample_info_immunochromatography with key = \"report_time\" where sample_name = '$sample_name'"
   },
   {
    "name": "pcr_positive_control",
    "query": "show tag values from sample_info_pcr with key = \"positive_control\" where sample_name = '$sample_name'"
   },
   {
    "name": "pcr_negative_control",
    "query": "show tag values from sample_info_pcr with key = \"negative_control\" where sample_name = '$sample_name'"
   }
  ]
 },
 "panels": [
  {
   "title": "样本：$sample_name ONT测序深度",
   "type": "bilibala-echarts-panel",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "position" ], "type": "tag" }
     ],
     "measurement": "reads_depth_stats",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "cell", "operator": "=~", "value": "/^$ont_cell$/" },
      { "condition": "AND", "key": "barcode", "operator": "=~", "value": "/^$ont_barcode$/" }
     ]
    }
   ]
  },
  {
   "title": "样本：$sample_name ONT测序读长",
   "type": "bilibala-echarts-panel",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "read_len" ], "type": "tag" }
     ],
     "measurement": "reads_length_stats",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "cell", "operator": "=~", "value": "/^$ont_cell$/" },
      { "condition": "AND", "key": "barcode", "operator": "=~", "value": "/^$ont_barcode$/" }
     ]
    }
   ]
  },
  {
   "title": "样本：$sample_name PCR定量曲线",
   "type": "bilibala-echarts-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"fluor\" FROM \"pcr_rdml_adp\" WHERE sample = '$pcr_run_well' GROUP BY \"sample\", \"tar\", \"cyc\" ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT \"fluor\" FROM \"pcr_rdml_adp\" WHERE sample = '$pcr_negative_control' GROUP BY \"sample\", \"tar\", \"cyc\" ",
     "select": [
      [
       { "params": [ "usage_idle" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"fluor\" FROM \"pcr_rdml_adp\" WHERE sample = '$pcr_positive_control' GROUP BY \"sample\", \"tar\", \"cyc\" ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": " 恒温荧光扩增PCR—算法计算后的曲线",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_channel_display",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"value\" FROM \"pcr_data\" GROUP BY \"channel_display\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "免疫层析结果",
   "type": "bilibala-echarts-panel",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "immunochromatography",
     "query": "SELECT \"tValue\" FROM \"immunochromatography\" WHERE (\"sampleID\" = '$immunochromatography_sample_id' AND \"reportTime\" = '$immunochromatography_report_time') GROUP BY \"tID\", \"tResult\"",
     "select": [
      [
       { "params": [ "tValue" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}