{
 "title": "PCR监控",
 "time": { "from": "2020-06-01T08:30:12.000Z", "to": "2020-06-01T09:09:42.000Z" },
 "panels": [
  {
   "title": " 恒温荧光扩增PCR—算法计算后的曲线",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "alias": "$tag_channel_display",
     "groupBy": [
      { "params": [ "channel_display" ], "type": "tag" }
     ],
     "measurement": "pcr_data",
     "query": "SELECT \"value\" FROM \"pcr_data\" GROUP BY \"channel_display\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "sn", "operator": "=", "value": "123_1_20200601171012" }
     ]
    }
   ]
  },
  {
   "title": "荧光定量PCR—CQ值",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_sample&$tag_tar($tag_excl)",
     "groupBy": [
      { "params": [ "sample" ], "type": "tag" },
      { "params": [ "tar" ], "type": "tag" },
      { "params": [ "id" ], "type": "tag" }
     ],
     "measurement": "pcr_rdml_cq",
     "query": "SELECT \"value\" FROM \"pcr_rdml_cq\" GROUP BY \"sample\", \"tar\", \"excl\",  \"ID\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "荧光定量PCR—定量曲线",
   "type": "bilibala-echarts-panel",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "sample" ], "type": "tag" },
      { "params": [ "tar" ], "type": "tag" },
      { "params": [ "cyc" ], "type": "tag" }
     ],
     "measurement": "pcr_rdml_adp",
     "query": "SELECT \"fluor\" FROM \"pcr_rdml_adp\" GROUP BY \"sample\", \"tar\", \"cyc\"",
     "select": [
      [
       { "params": [ "fluor" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "荧光定量PCR—熔点曲线",
   "type": "bilibala-echarts-panel",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "sample" ], "type": "tag" },
      { "params": [ "tar" ], "type": "tag" },
      { "params": [ "tmp" ], "type": "tag" }
     ],
     "measurement": "pcr_rdml_mdp",
     "query": "SELECT \"fluor\" FROM \"pcr_rdml_mdp\" GROUP BY \"sample\", \"tar\", \"tmp\"",
     "select": [
      [
       { "params": [ "fluor" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}